version: '2.7.0'
selector: rich_text_editor
simple_editor: false
body_class: yui-skin-sam
editor_extension_callbacks: "// MyExtension.install(editor);"
javascript_base_uri: //yui.yahooapis.com
editor_extension_javascripts:
  # - extension1.js
  # - extension2.js
additional_yui_javascripts:
  # - connection/connection
editor_config_javascript: "
{
  handleSubmit: true,
  autoHeight: false,
  dompath: false,
  collapse: false,
  toolbar: {
    collapse: true,
    draggable: false,
    buttonType: 'advanced',
    buttons: [
        { group: 'fontstyle',
            buttons: [
                { type: 'select', label: 'Arial', value: 'fontname', disabled: true,
                    menu: [
                        { text: 'Arial', checked: true },
                        { text: 'Arial Black' },
                        { text: 'Comic Sans MS' },
                        { text: 'Courier New' },
                        { text: 'Lucida Console' },
                        { text: 'Tahoma' },
                        { text: 'Times New Roman' },
                        { text: 'Trebuchet MS' },
                        { text: 'Verdana' }
                    ]
                },
                { type: 'spin', label: '13', value: 'fontsize', range: [ 9, 75 ], disabled: true }
            ]
        },
        { type: 'separator' },
        { group: 'textstyle',
            buttons: [
                { type: 'push', label: 'Bold CTRL + SHIFT + B', value: 'bold' },
                { type: 'push', label: 'Italic CTRL + SHIFT + I', value: 'italic' },
                { type: 'push', label: 'Underline CTRL + SHIFT + U', value: 'underline' },
                { type: 'separator' },
                { type: 'push', label: 'Subscript', value: 'subscript', disabled: true },
                { type: 'push', label: 'Superscript', value: 'superscript', disabled: true },
                { type: 'separator' },
                { type: 'color', label: 'Font Color', value: 'forecolor', disabled: true },
                { type: 'color', label: 'Background Color', value: 'backcolor', disabled: true },
                { type: 'separator' },
                { type: 'push', label: 'Remove Formatting', value: 'removeformat', disabled: true },
                { type: 'push', label: 'Show/Hide Hidden Elements', value: 'hiddenelements' }
            ]
        },
        { type: 'separator' },
        { group: 'alignment',
            buttons: [
                { type: 'push', label: 'Align Left CTRL + SHIFT + [', value: 'justifyleft' },
                { type: 'push', label: 'Align Center CTRL + SHIFT + |', value: 'justifycenter' },
                { type: 'push', label: 'Align Right CTRL + SHIFT + ]', value: 'justifyright' },
                { type: 'push', label: 'Justify', value: 'justifyfull' }
            ]
        },
        { type: 'separator' },
        { group: 'parastyle',
            buttons: [
            { type: 'select', label: 'Normal', value: 'heading', disabled: true,
                menu: [
                    { text: 'Normal', value: 'none', checked: true },
                    { text: 'Header 1', value: 'h1' },
                    { text: 'Header 2', value: 'h2' },
                    { text: 'Header 3', value: 'h3' },
                    { text: 'Header 4', value: 'h4' },
                    { text: 'Header 5', value: 'h5' },
                    { text: 'Header 6', value: 'h6' }
                ]
            }
            ]
        },
        { type: 'separator' },
        { group: 'indentlist',
            buttons: [
                { type: 'push', label: 'Indent', value: 'indent', disabled: true },
                { type: 'push', label: 'Outdent', value: 'outdent', disabled: true },
                { type: 'push', label: 'Create an Unordered List', value: 'insertunorderedlist' },
                { type: 'push', label: 'Create an Ordered List', value: 'insertorderedlist' }
            ]
        },
        { type: 'separator' },
        { group: 'insertitem',
            buttons: [
                { type: 'push', label: 'HTML Link CTRL + SHIFT + L', value: 'createlink', disabled: true },
                { type: 'push', label: 'Insert Image', value: 'insertimage' }
            ]
        }
    ]
  }
}"
